<script setup>
import { computed, onMounted, reactive, ref } from "vue";
import { ElMessage, ElMessageBox } from "element-plus";

import {
  createRecommendedTemplate,
  deleteRecommendedTemplate,
  listRecommendedTemplates,
  updateRecommendedTemplate,
  uploadRecommendedTemplateImage,
} from "../api/admin";

const loading = ref(false);
const saving = ref(false);
const uploadingImage = ref(false);
const dialogVisible = ref(false);
const pageErrorMessage = ref("");
const dialogErrorMessage = ref("");
const deletingTemplateId = ref(null);
const editingTemplateId = ref(null);
const autoGenerateFromImage = ref(true);
const templates = ref([]);

const form = reactive({
  name: "",
  template_type: "pose",
  source_image_url: "",
  preview_image_url: "",
  recommended_sort_order: 0,
  status: "active",
  template_data_text: "",
});

const dialogTitle = computed(() =>
  editingTemplateId.value ? "编辑推荐模板" : "新增推荐模板",
);

const templateJsonHint = computed(() =>
  autoGenerateFromImage.value
    ? "保存时会根据来源图片自动识别人姿并生成标准模板 JSON。"
    : "可手动粘贴或微调模板 JSON。建议优先使用图片自动生成。",
);

function normalizeText(value) {
  return typeof value === "string" ? value.trim() : "";
}

function resetForm() {
  editingTemplateId.value = null;
  dialogErrorMessage.value = "";
  autoGenerateFromImage.value = true;
  form.name = "";
  form.template_type = "pose";
  form.source_image_url = "";
  form.preview_image_url = "";
  form.recommended_sort_order = 0;
  form.status = "active";
  form.template_data_text = "";
}

function openCreateDialog() {
  resetForm();
  dialogVisible.value = true;
}

function openEditDialog(template) {
  resetForm();
  editingTemplateId.value = template.id;
  form.name = template.name ?? "";
  form.template_type = template.template_type ?? "pose";
  form.source_image_url = template.source_image_url ?? "";
  form.preview_image_url = template.preview_image_url ?? "";
  form.recommended_sort_order = Number(template.recommended_sort_order ?? 0);
  form.status = template.status ?? "active";
  form.template_data_text = JSON.stringify(template.template_data ?? {}, null, 2);
  autoGenerateFromImage.value = false;
  dialogVisible.value = true;
}

function buildPayload() {
  const name = normalizeText(form.name);
  const sourceImageUrl = normalizeText(form.source_image_url) || null;
  const previewImageUrl = normalizeText(form.preview_image_url) || sourceImageUrl;
  const templateDataText = normalizeText(form.template_data_text);
  const useAutoGeneratedData = Boolean(autoGenerateFromImage.value && sourceImageUrl);

  return {
    name,
    template_type: form.template_type,
    source_image_url: sourceImageUrl,
    preview_image_url: previewImageUrl,
    recommended_sort_order: Number(form.recommended_sort_order ?? 0),
    status: form.status,
    template_data: useAutoGeneratedData ? {} : templateDataText ? JSON.parse(templateDataText) : {},
  };
}

function formatDate(value) {
  if (!value) {
    return "-";
  }
  return new Date(value).toLocaleString("zh-CN");
}

function previewSummary(template) {
  const data = template.template_data ?? {};
  const bbox = Array.isArray(data.bbox_norm) ? data.bbox_norm.length : 0;
  const pointsSource =
    (data.pose_points_image && typeof data.pose_points_image === "object" && data.pose_points_image) ||
    (data.pose_points_bbox && typeof data.pose_points_bbox === "object" && data.pose_points_bbox) ||
    (data.pose_points && typeof data.pose_points === "object" && data.pose_points) ||
    null;
  const points = pointsSource ? Object.keys(pointsSource).length : 0;
  return `bbox ${bbox} / 点位 ${points}`;
}

async function loadTemplates() {
  loading.value = true;
  pageErrorMessage.value = "";
  try {
    templates.value = await listRecommendedTemplates();
  } catch (error) {
    pageErrorMessage.value = error.message || "推荐模板列表加载失败";
  } finally {
    loading.value = false;
  }
}

async function submitTemplate() {
  saving.value = true;
  dialogErrorMessage.value = "";
  try {
    const payload = buildPayload();
    if (!payload.name) {
      throw new Error("请先填写模板名称");
    }
    if (!payload.source_image_url && Object.keys(payload.template_data ?? {}).length === 0) {
      throw new Error("请上传模板图片，或手动填写模板 JSON");
    }

    if (editingTemplateId.value) {
      await updateRecommendedTemplate(editingTemplateId.value, payload);
      ElMessage.success("推荐模板已更新");
    } else {
      await createRecommendedTemplate(payload);
      ElMessage.success("推荐模板已创建");
    }
    dialogVisible.value = false;
    resetForm();
    await loadTemplates();
  } catch (error) {
    dialogErrorMessage.value = error.message || "推荐模板保存失败";
  } finally {
    saving.value = false;
  }
}

async function handleTemplateImageUpload(uploadRequest) {
  const file = uploadRequest?.file;
  if (!file) {
    return;
  }

  uploadingImage.value = true;
  dialogErrorMessage.value = "";
  try {
    const uploaded = await uploadRecommendedTemplateImage(file);
    form.source_image_url = uploaded.file_url ?? "";
    form.preview_image_url = uploaded.file_url ?? "";
    form.template_data_text = "";
    autoGenerateFromImage.value = true;
    ElMessage.success("模板图片已上传，保存时会自动生成人姿模板 JSON");
  } catch (error) {
    dialogErrorMessage.value = error.message || "模板图片上传失败";
  } finally {
    uploadingImage.value = false;
  }
}

async function confirmDelete(template) {
  try {
    await ElMessageBox.confirm(
      `确定删除推荐模板“${template.name}”吗？删除后手机端将不再显示它。`,
      "删除推荐模板",
      {
        type: "warning",
        confirmButtonText: "删除",
        cancelButtonText: "取消",
      },
    );
  } catch {
    return;
  }

  deletingTemplateId.value = template.id;
  pageErrorMessage.value = "";
  try {
    await deleteRecommendedTemplate(template.id);
    ElMessage.success("推荐模板已删除");
    await loadTemplates();
  } catch (error) {
    pageErrorMessage.value = error.message || "推荐模板删除失败";
  } finally {
    deletingTemplateId.value = null;
  }
}

onMounted(() => {
  loadTemplates();
});
</script>

<template>
  <div class="page-grid">
    <section class="glass-card panel-card">
      <div class="panel-head">
        <div>
          <h3>推荐默认模板</h3>
          <p>上传参考图片后，后台会自动识别人物姿势并生成完整模板 JSON，避免手填旧格式导致框线和姿态不准。</p>
        </div>
        <div class="panel-actions">
          <el-button type="primary" @click="openCreateDialog">新增推荐模板</el-button>
        </div>
      </div>

      <el-alert
        v-if="pageErrorMessage"
        class="panel-alert"
        type="error"
        :closable="false"
        :title="pageErrorMessage"
      />

      <el-table v-loading="loading" :data="templates" stripe class="data-table">
        <el-table-column prop="id" label="ID" min-width="80" />
        <el-table-column prop="name" label="模板名称" min-width="180" />
        <el-table-column prop="template_type" label="类型" min-width="120" />
        <el-table-column prop="recommended_sort_order" label="推荐排序" min-width="110" />
        <el-table-column label="数据摘要" min-width="180">
          <template #default="{ row }">
            {{ previewSummary(row) }}
          </template>
        </el-table-column>
        <el-table-column label="状态" min-width="100">
          <template #default="{ row }">
            <el-tag :type="row.status === 'active' ? 'success' : 'info'">{{ row.status }}</el-tag>
          </template>
        </el-table-column>
        <el-table-column label="更新时间" min-width="180">
          <template #default="{ row }">
            {{ formatDate(row.updated_at) }}
          </template>
        </el-table-column>
        <el-table-column label="操作" min-width="170" fixed="right">
          <template #default="{ row }">
            <div class="table-actions">
              <el-button link type="primary" @click="openEditDialog(row)">编辑</el-button>
              <el-button
                link
                type="danger"
                :loading="deletingTemplateId === row.id"
                @click="confirmDelete(row)"
              >
                删除
              </el-button>
            </div>
          </template>
        </el-table-column>
      </el-table>
    </section>

    <el-dialog
      v-model="dialogVisible"
      :title="dialogTitle"
      width="860px"
      destroy-on-close
      @closed="resetForm"
    >
      <div class="dialog-body">
        <el-alert
          v-if="dialogErrorMessage"
          class="panel-alert"
          type="error"
          :closable="false"
          :title="dialogErrorMessage"
        />

        <el-form label-position="top" class="dialog-form">
          <div class="form-grid">
            <el-form-item label="模板名称">
              <el-input v-model="form.name" maxlength="100" />
            </el-form-item>

            <el-form-item label="模板类型">
              <el-select v-model="form.template_type">
                <el-option label="姿态模板" value="pose" />
                <el-option label="背景模板" value="background" />
                <el-option label="构图模板" value="composition" />
              </el-select>
            </el-form-item>

            <el-form-item label="推荐排序">
              <el-input-number v-model="form.recommended_sort_order" :min="0" :max="999" />
            </el-form-item>

            <el-form-item label="状态">
              <el-select v-model="form.status">
                <el-option label="active" value="active" />
                <el-option label="archived" value="archived" />
              </el-select>
            </el-form-item>
          </div>

          <div class="form-grid">
            <el-form-item label="来源图片 URL">
              <el-input v-model="form.source_image_url" placeholder="可填写已上传图片地址，或使用下方上传按钮" />
            </el-form-item>

            <el-form-item label="预览图片 URL">
              <el-input v-model="form.preview_image_url" placeholder="默认会自动使用来源图片" />
            </el-form-item>
          </div>

          <el-form-item label="上传模板图片">
            <div class="template-upload-stack">
              <el-upload
                class="template-upload"
                drag
                :show-file-list="false"
                accept="image/jpeg,image/png,image/webp"
                :http-request="handleTemplateImageUpload"
                :disabled="uploadingImage"
              >
                <div class="upload-copy">
                  <strong>{{ uploadingImage ? "正在上传..." : "点击或拖拽上传模板图片" }}</strong>
                  <span>上传后保存，后台会自动识别人物姿势并生成完整模板 JSON。</span>
                </div>
              </el-upload>

              <div v-if="form.preview_image_url" class="template-preview-card">
                <img :src="form.preview_image_url" alt="模板预览" class="template-preview-image" />
              </div>
            </div>
          </el-form-item>

          <el-form-item label="模板 JSON 生成方式">
            <el-switch
              v-model="autoGenerateFromImage"
              active-text="从图片自动生成"
              inactive-text="手动编辑 JSON"
            />
            <div class="template-json-hint">{{ templateJsonHint }}</div>
          </el-form-item>

          <el-form-item label="模板数据 JSON">
            <el-input
              v-model="form.template_data_text"
              type="textarea"
              :rows="14"
              :disabled="autoGenerateFromImage"
              placeholder="请输入有效 JSON"
            />
          </el-form-item>
        </el-form>
      </div>

      <template #footer>
        <el-button @click="dialogVisible = false">取消</el-button>
        <el-button type="primary" :loading="saving" @click="submitTemplate">保存</el-button>
      </template>
    </el-dialog>
  </div>
</template>

<style scoped>
.page-grid {
  display: grid;
  gap: 18px;
}

.panel-card {
  padding: 22px;
}

.panel-head {
  display: flex;
  justify-content: space-between;
  align-items: flex-start;
  gap: 16px;
  margin-bottom: 18px;
}

.panel-head h3 {
  margin: 0 0 8px;
  font-size: 28px;
}

.panel-head p {
  margin: 0;
  color: var(--ca-muted);
  line-height: 1.7;
  max-width: 760px;
}

.panel-actions {
  display: flex;
  gap: 12px;
  flex-wrap: wrap;
}

.panel-alert {
  margin-bottom: 16px;
}

.data-table {
  width: 100%;
}

.table-actions {
  display: flex;
  align-items: center;
  gap: 8px;
}

.dialog-body {
  max-height: 74vh;
  overflow: auto;
  padding-right: 6px;
}

.dialog-form {
  display: grid;
  gap: 6px;
}

.form-grid {
  display: grid;
  grid-template-columns: repeat(2, minmax(0, 1fr));
  gap: 16px;
}

.template-upload-stack {
  display: grid;
  grid-template-columns: minmax(0, 1.3fr) minmax(240px, 0.7fr);
  gap: 16px;
  width: 100%;
}

.template-upload {
  width: 100%;
}

.upload-copy {
  display: grid;
  gap: 8px;
}

.upload-copy strong {
  color: var(--ca-text);
}

.upload-copy span,
.template-json-hint {
  color: var(--ca-muted);
  line-height: 1.7;
}

.template-preview-card {
  min-height: 220px;
  border: 1px solid rgba(255, 255, 255, 0.08);
  border-radius: 18px;
  overflow: hidden;
  background: rgba(255, 255, 255, 0.03);
}

.template-preview-image {
  display: block;
  width: 100%;
  height: 100%;
  min-height: 220px;
  object-fit: contain;
  background: rgba(4, 8, 14, 0.6);
}

@media (max-width: 960px) {
  .panel-head {
    flex-direction: column;
  }

  .form-grid,
  .template-upload-stack {
    grid-template-columns: 1fr;
  }
}
</style>
